### PR TITLE
Bugfix/odom twist worldframe

### PR DESCRIPTION
**Pull request by ClintLiddick**
- Merge updates from upstream master
- publish odom's twist component as velocities relative to base_link, rather than world

### CODE REVIEW

**Comment by mkoval** [comment]
I think you should actually send this pull request upstream. Is there any reason you made this pull request against our fork, instead?

**Comment by ClintLiddick** [comment]
Give you guys a chance to take a look, and can make the upstream request from the lab. I can make the pull request myself if that makes more sense.

**Comment by mkoval** [comment]
Sounds good to me.

**Comment by mkoval** [comment]
I sent this upstream here: https://github.com/segwayrmp/segway_rmp/pull/28.

**Pull request merged**
